events {}
http {
    server {
        listen 80;
        server_name localhost;

        # Whitelist IP chi nhanh (Lap phong thu 1)
        allow 192.168.1.0/24; # Da.i IP noi bo branch TP1
        allow 10.0.0.0/8;     # VPN
        deny all;

        location / {
            proxy_pass http://branch-tp1-app:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
