package com.storename.erp.test;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertNotNull;

@SpringBootTest
@ActiveProfiles("postgres-it")
public class PostgresSpecificFeaturesIT extends PostgresIntegrationTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    /**
     * Schema dựa vào hàm gen_random_uuid() có sẵn trong PostgreSQL 13+ (không cần extension),
     * vd. user_account.public_id DEFAULT gen_random_uuid() (db/migration/V1__identity_and_branch.sql)
     * và các script vận hành. Trước đây test gọi uuid_generate_v4() của extension uuid-ossp —
     * extension này chưa bao giờ được tạo và ứng dụng không dùng.
     */
    @Test
    void testGenRandomUuidFunctionExists() {
        String generatedUuidStr = jdbcTemplate.queryForObject("SELECT gen_random_uuid()::text", String.class);

        assertNotNull(generatedUuidStr, "UUID generated by PostgreSQL native function should not be null");
        UUID uuid = UUID.fromString(generatedUuidStr);
        assertNotNull(uuid);
    }

    @Test
    void testUserAccountPublicIdDefaultsToRandomUuid() {
        String columnDefault = jdbcTemplate.queryForObject(
                "SELECT column_default FROM information_schema.columns WHERE table_schema = current_schema() "
                        + "AND table_name = 'user_account' AND column_name = 'public_id'",
                String.class);
        assertNotNull(columnDefault);
        org.junit.jupiter.api.Assertions.assertTrue(columnDefault.contains("gen_random_uuid()"),
                "user_account.public_id phải mặc định gen_random_uuid(), thực tế: " + columnDefault);
    }
}
