package com.storename.erp.test;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertNotNull;

@SpringBootTest
@ActiveProfiles("postgres-it")
public class PostgresSpecificFeaturesIT extends PostgresIntegrationTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Test
    void testUuidGenerateV4FunctionExists() {
        // Attempt to call the uuid_generate_v4() function.
        // If the extension "uuid-ossp" is missing, this will throw a DataAccessException (function does not exist).
        // H2 in-memory DB cannot effectively validate this native extension.
        String generatedUuidStr = jdbcTemplate.queryForObject("SELECT uuid_generate_v4()", String.class);
        
        assertNotNull(generatedUuidStr, "UUID generated by PostgreSQL native function should not be null");
        
        // Parse it to ensure it's a valid UUID
        UUID uuid = UUID.fromString(generatedUuidStr);
        assertNotNull(uuid);
    }
}
