-- ============================================================================
-- V1 — Module identity + branch
-- Chạy trên HQ và MỌI chi nhánh (schema giống hệt nhau).
-- Owner dữ liệu: HQ. Replicate HQ -> Branch (xem scripts/replication-tables.conf).
-- ============================================================================

-- Chi nhánh. id là số (BIGINT) vì JWT claim `branchId` và biến BRANCH_ID của app chi nhánh dùng id này.
CREATE TABLE branch (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(20)  NOT NULL UNIQUE,
    name            VARCHAR(200) NOT NULL,
    address         VARCHAR(500),
    phone           VARCHAR(20),
    opening_hours   VARCHAR(100),
    -- URL cổng SPA chi nhánh mà trình duyệt truy cập (frontend dùng để chặn STAFF đăng nhập nhầm cổng).
    internal_url    VARCHAR(255),
    is_active       BOOLEAN      NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE role (
    id      SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    VARCHAR(50)  NOT NULL UNIQUE,
    name    VARCHAR(200) NOT NULL
);

CREATE TABLE permission (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE role_permission (
    role_id         SMALLINT NOT NULL,
    permission_id   SMALLINT NOT NULL,
    PRIMARY KEY (permission_id, role_id),
    CONSTRAINT fk_role_permission_role       FOREIGN KEY (role_id)       REFERENCES role (id),
    CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES permission (id)
);

CREATE TABLE user_account (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Định danh công khai (JWT subject). Cột audit created_by/updated_by ở các bảng khác là UUID này.
    public_id       UUID         NOT NULL DEFAULT gen_random_uuid(),
    username        VARCHAR(100) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    full_name       VARCHAR(200) NOT NULL,
    email           VARCHAR(200),
    phone           VARCHAR(20),
    is_active       BOOLEAN      NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX ux_user_account_public_id ON user_account (public_id);

-- branch_id NULL = vai trò toàn hệ thống (ADMIN tại HQ); STAFF bắt buộc có branch_id.
CREATE TABLE user_branch_role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT   NOT NULL,
    role_id     SMALLINT NOT NULL,
    branch_id   BIGINT,
    CONSTRAINT fk_user_branch_role_user   FOREIGN KEY (user_id)   REFERENCES user_account (id),
    CONSTRAINT fk_user_branch_role_role   FOREIGN KEY (role_id)   REFERENCES role (id),
    CONSTRAINT fk_user_branch_role_branch FOREIGN KEY (branch_id) REFERENCES branch (id)
);
