-- ============================================================================
-- V2 — Module catalog: danh mục, sản phẩm, nhà cung cấp, bảng giá
-- Chạy trên HQ và MỌI chi nhánh. Owner dữ liệu: HQ. Replicate HQ -> Branch.
-- ============================================================================

CREATE TABLE category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL UNIQUE,
    name        VARCHAR(200) NOT NULL,
    parent_id   BIGINT,
    is_active   BOOLEAN      NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES category (id)
);

CREATE TABLE product (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(50)  NOT NULL UNIQUE,
    name                VARCHAR(200) NOT NULL,
    category_id         BIGINT       NOT NULL,
    base_unit           VARCHAR(50)  NOT NULL,
    attributes_cache    JSONB,
    is_active           BOOLEAN      NOT NULL,
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category (id)
);

-- Nhà cung cấp: dữ liệu DÙNG CHUNG toàn hệ thống (không có branch_id).
-- id do ứng dụng sinh (UUID), code do người dùng/frontend đặt.
CREATE TABLE supplier (
    id          UUID         PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    phone       VARCHAR(20),
    email       VARCHAR(255),
    address     VARCHAR(500),
    tax_code    VARCHAR(50),
    is_active   BOOLEAN      NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- Giá bán theo (sản phẩm, chi nhánh). Ứng dụng đọc 1 giá cho mỗi cặp (ProductReader dùng Collectors.toMap).
CREATE TABLE price_list (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT        NOT NULL,
    branch_id       BIGINT        NOT NULL,
    price           NUMERIC(19,4) NOT NULL,
    effective_date  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_price_list_product FOREIGN KEY (product_id) REFERENCES product (id),
    CONSTRAINT fk_price_list_branch  FOREIGN KEY (branch_id)  REFERENCES branch (id)
);
