-- ============================================================================
-- V6 — Module analytics: bảng chiều thời gian và bảng sự kiện (data warehouse tại HQ)
-- Chạy trên HQ và MỌI chi nhánh (giữ schema giống nhau). Không replicate.
-- ============================================================================

CREATE TABLE dim_date (
    date_key    INTEGER  PRIMARY KEY,   -- yyyymmdd
    full_date   DATE     NOT NULL,
    year        SMALLINT NOT NULL,
    month       SMALLINT NOT NULL,
    day         SMALLINT NOT NULL
);

CREATE TABLE fact_sales (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_key        INTEGER       NOT NULL,
    invoice_id      UUID          NOT NULL,
    product_id      BIGINT        NOT NULL,
    branch_id       BIGINT        NOT NULL,
    customer_id     UUID          NOT NULL,
    quantity        NUMERIC(18,3) NOT NULL,
    unit_price      NUMERIC(18,2) NOT NULL,
    unit_cost       NUMERIC(18,4) NOT NULL,
    revenue         NUMERIC(18,2) NOT NULL,
    gross_profit    NUMERIC(18,2) NOT NULL
);

CREATE TABLE fact_stock_movement (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_key        INTEGER       NOT NULL,
    product_id      BIGINT        NOT NULL,
    branch_id       BIGINT        NOT NULL,
    movement_type   VARCHAR(20)   NOT NULL,
    quantity        NUMERIC(18,3) NOT NULL
);
