-- V2__catalog_schema.sql
-- Triển khai module Catalog: Category, Product, Attribute (EAV 3NF), PriceList

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES category(id)
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    base_unit VARCHAR(50) NOT NULL,
    attributes_cache JSONB, -- Điểm phá chuẩn (Denormalize) theo giai-thich-chuan-hoa-database.md
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE attribute_definition (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    data_type VARCHAR(50) NOT NULL -- e.g., TEXT, NUMBER, BOOLEAN
);

CREATE TABLE category_attribute (
    category_id BIGINT NOT NULL,
    attribute_id SMALLINT NOT NULL,
    PRIMARY KEY (category_id, attribute_id),
    CONSTRAINT fk_catattr_category FOREIGN KEY (category_id) REFERENCES category(id),
    CONSTRAINT fk_catattr_attribute FOREIGN KEY (attribute_id) REFERENCES attribute_definition(id)
);

CREATE TABLE product_attribute_value (
    product_id BIGINT NOT NULL,
    attribute_id SMALLINT NOT NULL,
    value_text VARCHAR(500),
    value_number NUMERIC(19,4),
    value_boolean BOOLEAN,
    PRIMARY KEY (product_id, attribute_id),
    CONSTRAINT fk_prodattrval_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE,
    CONSTRAINT fk_prodattrval_attribute FOREIGN KEY (attribute_id) REFERENCES attribute_definition(id)
);

CREATE TABLE price_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    price NUMERIC(19,4) NOT NULL,
    effective_date TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pricelist_product FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT fk_pricelist_branch FOREIGN KEY (branch_id) REFERENCES branch(id)
);

-- Index cho tìm kiếm và đọc theo hot path
CREATE INDEX ix_product_category ON product(category_id);
CREATE INDEX ix_product_attributes_cache ON product USING GIN (attributes_cache);
CREATE INDEX ix_pricelist_lookup ON price_list(product_id, branch_id, effective_date DESC);
